### ISSUE TITLE
README 작성

### ISSUE THREAD

**Issue by f-lab-kevin** [D-Scrumble/frontend#2]
README는 프로젝트가 어떤 모습인지에 대해 필요한 정보들을 한눈에 볼 수 있도록 작성해주시면 좋을 것 같아요!
고민해보시고 어떤 정보들이 필요할 지 여러 오픈소스 프로젝트들을 참고해보시면 좋을 것 같습니다!

**Comment by havenothorn** [comment]
PR 생성하였습니다! 검토 부탁드립니다 
[DSB-09](https://github.com/D-Scrumble/frontend/pull/3)
